### ISSUE TITLE
Moving Support to In-App

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/meta#105]
We're changing how support at PostHog works and, as a result, there are a bunch of things which we should either update or discuss. This issue is part checklist to make sure we don't miss anything and part thinkpiece about what the impacts may be. 

### What's changing?
- We are no longer offering public community support via Slack
- We are no longer offering support or any contact through hey@posthog.com
- We, as much as possible, want to encourage all bug reports, support requests and more to be made through the app. As a result, we no longer want to encourage users to create issues, email us, or post in Slack. 

The rationale for making these changes is that, by funnelling requests through the app, we can more effectively triage them and give users a better experience. We can also better prioritize requests.

### What needs to be updated/done?
We need the [external/internal linking
](https://github.com/PostHog/posthog/issues/15114) capability to merge in, and then update links in a lot of places. This would allow us to have a link which directs support requests into the app, and to the modal. 

- [x] Every mention on the site of using Slack to talk to engineers, or get community support.
- [x] Every mention on external sites that mentions joining the Slack, or asks users to contact us via hey@posthog.com (Bookface, G2, etc.)
- [x] We should announce the change to users via Slack and the Changelog
- [ ] Potentially: We should announce the change to all non-paying users via email
- [x] We should rename the Community Support channel to Community
- [x] We should archive the Inspiration, Introductions and any other channels which will not be used heavily.
- [ ] We should update the welcome bot (or [MaxAI](https://github.com/PostHog/max-ai/issues/4)) to alert users that support requests in Slack will not be seen

Potentially, we should archive the existing Community channel and create a new version from scratch, to remove all the support questions from there?

## Open questions
There are two big questions which I haven't seen a clear answer proposed for. 

### What about the Slack?
An obvious side effect of funnelling all user feedback and support requests into the app is that there will be really no reason left for people to use the Slack channel. 

One solution is that we doubledown on turning the Slack into our contributor/beta community, so that everyone in a beta is added there and we engage with them there for real-time feedback. 

Another opportunity would be to invest in making the Slack a _true_ community and we put together a schedule of community events and opportunities to galvanise this. This would be non-trivial and is something that should be planned in a separate issue. 

The final option is that we should simply close the Slack, or not make any further changes. Obviously not a very desirable outcome.

### What about Squeak questions?
In addition to the Slack, we also funnel users towards `/questions` to get support. 

I'm unclear on what the plan is in this regard if, as has been discussed, we want to funnel _all_ bug reports, support requests and product feedback through the app. Are these questions going to remain? Will this be the new 'Community Support' channel? If not, should we remove 'Community Support'?

**Comment by charlescook-ph** [comment]
> Potentially: We should announce the change to all non-paying users via email

If we're announcing this in Slack and people are getting an autoresponse from hey@ I don't think we also need to do this

**Comment by corywatilo** [comment]
There are three common interactions we have with customers:

1. Product usage/use case question
2. I have a specific issue with my account and need private help (or report a bug)
3. General feedback

I agree we should make #1 public (so others can benefit from the answers) and #2 and #3 should be somewhere else. And we should make it clear in both places what the purposes are for both forms.

## Why did we move away from Slack?

On Slack, there were a lot of use case questions. We'd answer them, but the threads would quickly disappear because of Slack's data retention limit on free accounts. That's where Squeak! came in. We wanted a way for all of that rich knowledge to live on.

## Why not Zendesk?

There are a few issues:

**1. Volume is growing, and we don't have the capacity to respond to everyone individually.** This leads to customers feeling like we don't care about them if they're not paying us. Ideally we want every customer to feel valued.
**2. We end up answering the same questions repeatedly** (even if answers are documented in the docs)
**3. We lose a lot of threads in the transfer between support heros** and users end up _not_ getting resolutions

## What do other companies do?

Forums are a common way to make knowledge publicly available and allow power users to jump in and help answer questions (in addition to staff). A great example is [Fly.io's community](https://community.fly.io/).

## What makes sense for us?

**1. Product usage/use case question = public**, so this can be indexed, and others can benefit from replies
**2. Specific account issue / bug = ticket-based** makes sense
**3. General feedback = no strong feelings (I liked our app)** but we just need to make it clear you shouldn't expect a response

## Concerns about Squeak!

**1. Some questions need context** - we're working on that, considering [adding Sidecar to the website](https://posthog.slack.com/archives/C049N8NU90B/p1681792111487159) for our internal users
**2. Answers should be incorporated into docs** - agreed, though there's a strong case for "FAQs" and the questions section inline in docs serve as that
**3. Answers can get out of date** - we're going to add some sort of archive option to handle this
**3. Who's responsible for which questions? Ultimately each small team** should own questions being asked in their section of the website, docs, or forums. We're adding subscription options and reminders to help with this.

[More details](https://github.com/PostHog/posthog.com/issues/5690) about what I'm driving to help improve question asking/answering on posthog.com

**Comment by joethreepwood** [comment]
I'm not sure this really answers the question of what's happening with Slack and how/if Squeak will become the community support option?

**Comment by simfish85** [comment]
If I'm not mistaken Squeak will still be answered/moderated by the PostHog team?  Maybe long term we have community engagement there but not yet.

**Comment by joethreepwood** [comment]
My suggestion/proposal based on the comments and direction above is that we, over the next few weeks, take the following steps: 

- [ ] Wait for the[ internal/external link feature](https://github.com/PostHog/posthog/issues/15114) to drop, so we can effectively link to the support modal from Slack. 
- [ ] Formally announce to the Slack community that we'll no longer provide support through there, and that they should post all support requests through the app. Users can continue to ask Max-AI for help. 
- [ ] [Update Max-AI to become the welcome bot for Slack](https://github.com/PostHog/max-ai/issues/4), reinforcing this message and driving adoption. 
- [ ] Update all content (pricing table, etc) so that Community Support = `posthog.com/questions` 

I'd appreciate feedback or vocal agreement on this, as it'll obviously be a very visible issue. 

I'd be happy to handle all comms and site updates to make this happen in an upcoming sprint, though would need help from Team Bandwagoneers (@fuziontech 🤞 ) to make the Welcome Bot changes.

**Comment by joethreepwood** [comment]
Going to close this for now, as it's stale and most of the stuff is either done or low prio
