### ISSUE TITLE
Hog/QL tasklist

### ISSUE THREAD

**Issue by mariusandra** [PostHog/meta#208]
Consolidating ideas and todos regarding the Hog language. There's another list to track the [HogQL todos](https://github.com/PostHog/meta/issues/81), and this does not directly touch upon the CDP projects. This list is a work in progress.

### Todo

- [x] Objects, arrays, tuples and nested assignment
- [ ] Make a decision on string quotes and dict keys
- [ ] Make a decision on array indexes starting with 0 vs 1
- [ ] Implement lambdas and closures
- [ ] Types for variables and function arguments / return
- [ ] Run the same set of tests for both python and typescript VMs
- [ ] ...
