### ISSUE TITLE
Q3 Mega-issue: Joe's Goals

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/meta#215]
My goals this quarter are more numerous, so I'm putting everything in one issue. Here we go. 

## Goal 1: Make sure we have successful launch plans for new products

- [x] [Data Warehouse launch](https://github.com/PostHog/meta/issues/227)
- [x] [Web Analytics launch](https://github.com/PostHog/meta/pull/179)
- [ ] Mobile Replay launch
- [x] [Launch Onboarding 6.0 to support new growth strategy](https://github.com/PostHog/meta/issues/212)
- [x] [Replay price cut launch](https://github.com/PostHog/meta/issues/227)
- [x] [Personless profiles launch](https://github.com/PostHog/meta/issues/227)

## Goal 2: Run another YC S24 campaign, but with less direct work

- [x] Add the PMF guide to the YC kit
- [x] Run the YC kit as before, with no additional work
- [x] Arrange/support a Tim & James talk in SF if the opportunity arises
- [x] Report on success internally as the program continues
- [x] Arrange a talk with another startup accelerator to try and open a new partnership (Founders.inc)

## Goal 3: Onboard ~community manager~ 3x support engineers
[Context for changes](https://posthog.slack.com/archives/C017WDX3BFZ/p1725293116540569)

- [ ] ~Hire a Community Manager and complete their onboarding~
- [ ] ~Get that person set up for success, with their own Q3 goals~
- [ ] ~Arm that person to find two more influencers we can work with~
- [x] Add [a new hire onboarding flow](https://posthog.slack.com/archives/C0351B1DMUY/p1721295672678619) to help support new team members 
- [x] Hire one support engineer, and get them onboarded, set up for handling tickets
- [x] Hire another support engineer, do the same
- [x] Hire _another_ support engineer, get them set up 
- [x] Explore community support engineer as a focus

## Goal 4: Continue to support CS & Sales

- [x] Get the SF x C.io pipeline working, or find a replacement
- [x] Create an automated email flow for demo follow-ups
- [x] [Create an automated process for users on timed programs (YC + Startups)](https://posthog.slack.com/archives/C043VJ93L3B/p1722009222340959?thread_ts=1721754848.379339&cid=C043VJ93L3B)
- [x] Continue to arm CS & Sales with case studies for all new products
- [x] Create a long-term nurture flow for unconverted users from demos
- [x] https://github.com/PostHog/posthog/issues/22036

**Comment by charlescook-ph** [comment]
This is a great list!
