### ISSUE TITLE
Launch Plan: Warehouse, Replays & Person Profiles 

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/meta#227]
We've got a lot of big things to announce over the next few weeks, and while we have an issue for each item in particular we decided it was getting difficult to keep everything straight due to dependencies and delays. So, I'm putting together a launch plan that unites all three announcements and lays out the order that has been decided by @zlwaterfield @annikaschmid and I. 

Going forward we'll use this issue to keep everything on track and make further decisions about the launches and announcements (but not the product). 

## Context and owners
We previously created these three separate issues for planning the launches. Each of these is up to data and _should be kept up to date with technical information by the product owner_. This issue is just to help us plan the announcement strategy, not make product decisions. 

- Data Warehouse: [Launch plan](https://github.com/PostHog/meta/pull/209), owned by @EDsCODE 
- Replay price cut: [Launch plan](https://github.com/PostHog/company-internal/issues/1311), owned by @annikaschmid 
- Person profiles: [Launch plan](https://github.com/PostHog/product-internal/pull/583/), owned by @zlwaterfield / @raquelmsmith 

## What order are we announcing things in?

**Week beginning July 15th:** Data warehouse
**Week beginning July 22nd:** Session replay price cut
**Week beginning July 29th:** Person profiles

We've decided not to combine these announcements in order to increase the visibility of each and to simplify the messaging for each announcement. We want to create an impression that PostHog is the highest value platform and is constantly driving down prices -- separating the announcements (with follow-on) best enables us to do that. 

We've decided to announce person profiles last because it is the most complex announcement and there is outstanding work to do around merging profiles. This timing enables us to have greater confidence in getting that done before launch, whereas we're more confident that replay will be ready in time. 

We're putting each of these announcements a week apart to simplify messaging, but also because of the calendar timings and volumes of emails sent. We limit Customer.io to sending approx 1,000 emails per hour in order to improve deliverability rates and avoid spam filters. As a result, mass comms to all users will take between 48-36 hours to complete.

### Week beginning July 15th 

Happy to report that at time of writing most of this is already underway. 

Messaging for the data warehouse is focused on use-cases. We don't want to highlight the data warehouse itself, or fall into the trap of having to educate users about what a data warehouse is as an abstract concept. We want to instead highlight the potential uses. It's not about being able to pipe data in. It's about what you can do when you have your Stripe (or whatever) data in the same tool as your Hubspot (or whatever) data, plus comprehensive analysis tooling. 

- [x] Publish a [Stripe data warehouse tutorial](https://github.com/PostHog/posthog.com/issues/8662)
- [x] Publish a [Hubspot data warehouse tutorial](https://github.com/PostHog/posthog.com/issues/8664)
- [x] Publish a [Zendesk data warehouse tutorial](https://github.com/PostHog/posthog.com/pull/8858)
- [x] [Add Data Warehouse to in-app 'Explore the docs' menu](https://github.com/PostHog/posthog/pull/22715) 
- [x] [Release Data Warehouse product page](https://github.com/PostHog/posthog.com/pull/8875)
- [x] Release Data Warehouse pricing page
- [x] [Release Data Warehouse case study](https://github.com/PostHog/posthog.com/pull/8875)
- [x] [Release Data Warehouse announcement post](https://github.com/PostHog/posthog.com/pull/8887)
- [x] [Email announcement to beta users](https://github.com/PostHog/meta/issues/213)
- [x] [Email announcement to new users](https://github.com/PostHog/meta/issues/213)
- [x] [Email reminder for beta users](https://github.com/PostHog/meta/issues/213)
- [x] Add Data Warehouse announcement to changelog - @joethreepwood 
- [x] Send Data Warehouse pylon announcement - @joethreepwood 
- [x] Send Data Warehouse changelog announcement in-app - @joethreepwood 

### Week beginning July 22nd

[Link to pricing changes](https://posthog.slack.com/files/U02QPCBE9S7/F07D9TCRLRE/231026_-_session_replay_competitor_pricing).

Messaging for session replay will focus on us committing to be as cheap as we can be while remaining margin positive. We recognised that we could give greater value to user by cutting prices, so thats simply what we're doing. The new plan offers greater value for all new users, and most existing users except for a small handful who are on legacy plans. 

- [x] [Legacy plan migration](https://github.com/PostHog/meta/issues/225)
- [x] [Comparison art for new replay pricing](https://github.com/PostHog/posthog.com/issues/8977) - @lottiecoxon 
- [x] Update pricing page - @annikaschmid 
- [x] Changelog announcement - @joethreepwood 
- [ ] Update comparison pages where relevant - @andyvan-ph 
- [x] Social media posts for the announcement - @andyvan-ph
- [x] Blog post announcing change - @andyvan-ph  
- [x] [Email for existing users not on a legacy plan](https://github.com/PostHog/meta/issues/228) - @joethreepwood 
- [x] [Email for existing users on a legacy plan](https://github.com/PostHog/meta/issues/228) - @joethreepwood 

### Week beginning July 29th

We're calling person profiles 'identified events' and those without person profiles 'anonymous events'. We're announcing this as a new event processing option which gives users greater control of what data they collect and pay for. Anonymous events are cheaper and will be the default for all events going forward. Again, we'll focus on highlighting usecases for anonymous and identified events. We'll tell existing users that they can alter their config to start saving money now.

As this is the final announcement in the trilogy we'll also include a wider blog post that explains the overall strategy and why we're lowering prices in this way, emphasizing our commitment to providing the best value. This will be replicated on Twitter.

- [x] [Beta invite](https://github.com/PostHog/meta/issues/198)
- [x] Update pricing page, calculator, etc - @corywatilo 
- [x] [Readme updates](https://github.com/PostHog/posthog/pull/22844)
- [x] [Key art](https://github.com/PostHog/posthog.com/issues/8248) 
- [x] [Docs updates for new terminology](https://github.com/PostHog/posthog.com/pull/9054) - @ivanagas 
- [ ] [Email announcement](https://github.com/PostHog/meta/issues/196) - @joethreepwood  
- [ ] Changelog entry - @joethreepwood 
- [ ] In-app notification - @joethreepwood 
- [ ] Pylon broadcast - @joethreepwood 
- [x] Blog post focusing on wider pricing strategy - @andyvan-ph ([previously](https://github.com/PostHog/posthog.com/pull/8802))
- [ ] Share strategy blog post to Hacker News - Marketing
- [ ] Replicate strategy blog post on James' Twitter - @jamesefhawkins 
- [ ] Create Customer.io campaign based on migration event - @joethreepwood & @raquelmsmith 

Once all the announcements are live I'll also run them into the Startups, YC, Onboarding, and Changelog emails where relevant and as needed.

**Comment by joethreepwood** [comment]
I'm going to be away for a few days, and it's looking like we may be setup to send some of the replay and personless emails while I'm away. So, I've created a handover doc which explains what actions are needed -- most of it is setup, there's just one segment and some complex targeting to set. It's all explained here: https://docs.google.com/document/d/1vGjRtMrNc1nYPo0rYALoFcMexeDtirSEsJE9nRh3rYI/edit?usp=sharing

I'm hoping that @andyvan-ph or @ivanagas will be able to jump in and take responsibility for these if needed!

**Comment by andyvan-ph** [comment]
For my sins, I will pick up email stuff.

**Comment by joethreepwood** [comment]
<img width="1202" alt="Screenshot 2024-08-15 at 14 50 05" src="https://github.com/user-attachments/assets/ea3e1d00-4955-4f5b-aead-b9efe113f34e">

@raquelmsmith as per your request, a new 1 week warning for beta users. It'll go out on Aug 26th.
