### ISSUE TITLE
Q4 2024: Joe's Goals

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/meta#243]
## Q4 Plans
I'll update this with more ideas as I go. 

## Centralize and improve all email comms
- [x] Roll out a new email design for dark mode to all email campaigns
- [x] [Get all billing comms into Customer.io](https://github.com/PostHog/meta/issues/237)
- [ ] Get all ops (e.g. password reset) comms into Customer.io
- [ ] Get any possible community comms into Customer.io too
- [x] [Replay Recommender](https://github.com/PostHog/meta/issues/253)
- [x] Optimize the onboarding flow for beta access where possible
- [x] Be the guinea pig for the messaging product
- [x] [Tweak the onboarding flow to prioritize general templates over AARRR](https://posthog.slack.com/archives/C011L071P8U/p1727692544555119)
- [x] [New Teams Upsell process](https://github.com/PostHog/meta/issues/247)
 
## Make sure our upcoming betas and product launches are successful
- [ ] Error tracking product
- [ ] AI analytics product
- [x] [Mobile replay product](https://github.com/PostHog/meta/issues/256)
- [ ] Referral product?

## Sidequest: Supercharge F24 and Startups program 
- [x] [The YC Supergroup](https://github.com/PostHog/company-internal/issues/1525)
- [x] [The new congrats merch package for fundraisers](https://github.com/PostHog/posthog.com/issues/9456)
- [x] [Hire a new product marketer to help scale efforts here](https://github.com/PostHog/company-internal/issues/1531)
- [x] Explore getting PostHog on GetProven to roll us out to 100 additional VCs
- [x] [Roll out the new $500 bonus for Startups](https://posthog.slack.com/archives/C01FHN8DNN6/p1727789549419059) 
- [x] [Startups Onboarding 2.0](https://github.com/PostHog/meta/issues/245)
- [x] [Startups Onboarding 3.0](https://github.com/PostHog/meta/issues/249)

## Sidequest: Support CS & Sales
- [x] ~1x Enterprise case study ([Airbus](https://github.com/PostHog/posthog.com/issues/9297))~ ([we should tick this](https://posthog.slack.com/archives/C01MGUHFH6G/p1732890074641609))
- [x] 1x Accessible case study ([Octomind](https://github.com/PostHog/posthog.com/issues/9508))
- [x] 1x Marketing case study ([Great Expectations](https://github.com/PostHog/posthog.com/issues/9522))
- [x] 1x Mobile case study ([Swype](https://github.com/PostHog/posthog.com/pull/9696))

## Anti-goals 
- [x] Don’t waste a bunch of time on boring partnerships

**Comment by zlwaterfield** [comment]
Can I add an exploratory comment about _email subscription management_? I'd love to come up with a solid structure of email types and whether or not they are subscribed and then pipe that into postage so we can have a UI for managing it.

**Comment by joethreepwood** [comment]
Can you explain what you mean a bit there? 

We currently have subscription topics set up in Customer.io and can use that UI for analysis, etc, gives people the option to manage most of their subscriptions too. We override this for billing, obviously.

**Comment by zlwaterfield** [comment]
Okay, I just clicked unsubscribe on one of the emails and then clicked manage subscriptions, and I see we have four categories. I didn't realize we broke them out like this. 

![Screenshot 2024-09-30 at 10 08 49 AM](https://github.com/user-attachments/assets/2ff3658e-69c1-485f-b8e8-7188fc7b4567)

Moving to c.io will solve what I was getting at, so I think we are good. At some point, we should sync these into PostHog so they can edit them in their settings.

**Comment by techcraver** [comment]
My favorite part is the anti-goals. :D

**Comment by joethreepwood** [comment]
### 360 Feedback
We had our 360 feedback session at the Palm Springs offsite, which was our first as a Comms Team and my first team lead. Historically I have written up my feedback as issues or PRs (see [this](https://github.com/PostHog/posthog.com/pull/3288), and [this](https://github.com/PostHog/posthog.com/pull/4596)). This time, to stop cluttering the repos, I'll just add it here. 

I do this mainly as an invitation to get more feedback from other people, rather than for clarification purposes. I've already asked @ivanagas @corywatilo @andyvan-ph @charlescook-ph and @jamesefhawkins for additional feedback - and this create a relevant, transparent place to add it. It's also an opportunity for me to reflect on it. 

### Feedback from Nov 20 session

**Positive feedback**
- There was feedback that people recognize the breadth and volume of my work. They feel I work across a lot of different areas and that I give support an equal balance/priority compared to other things. 
- There was feedback that I represent the team well internally, both by giving context to other teams so they don't make wrong assumptions about team performance, and also by backing up individuals when it's needed and taking responsibility.
- There was feedback that the team found me approachable and greatly enjoyed working with me. They like that I don't try to micromanage things and that they're empowered to make decisions themselves. 

**Mixed feedback**
- There was mixed feedback on how I am during 1:1s. Some felt I had a calming presence and an enjoyable, conversational style. Others felt I was easily distracted during calls and that they'd benefit from additional structure in these discussions. 

**Constructive feedback**
- There was a feedback that I'm better at relaying big plans or fine detail than general feedback on overall performance, especially during probationary periods. 
- There was some concern that I have too much on and that I won't be able to sustain giving support enough attention as the team grows. Sometimes I can miss details in pursuit of the bigger picture. 
- There was feedback that I keep sprint plans too focused on work and don't embrace them as a chance to socialize and build rapport with the team. 

## Actions based on feedback
There are some things I'll try to roll in to my Q4 goals so I can improve this quarter...

- [ ] Keep doing the good things, obviously. That's easy. 
- [ ] Speak to team members to understand how I can adapt the 1:1s to suit individual needs (and do that)
- [ ] Hire the new product marketer to help ease off the workload a bit
- [ ] Don't end sprint meetings ahead of time so often; chat more if people want to stay
