### ISSUE TITLE
Insight Variables TODO

### ISSUE THREAD

**Issue by Gilbert09** [PostHog/meta#255]
## Todo:
- [x] Internal beta
  - [x] Create variables
  - [x] Apply variables to HogQL
  - [x] Roll up variables on dashboards
  - [x] Edit variables
  - [ ] Delete variables
- [ ] GA release
- [ ] Add date variables
  - [ ] Date range
  - [ ] Single date
- [ ] Support trends 
- [ ] Support funnels
- [ ] Drop-down variables backed by SQL
- [ ] Property variable
- [ ] Replace existing filters for insight variables

[Internal link](https://github.com/PostHog/product-internal/pull/651)

**Comment by abigailbramble** [comment]
Related tickets:
https://posthoghelp.zendesk.com/agent/tickets/19773 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/22362)
https://posthoghelp.zendesk.com/agent/tickets/20180 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/22872)
https://posthoghelp.zendesk.com/agent/tickets/20569 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/22329)
https://posthoghelp.zendesk.com/agent/tickets/21313 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/27946)
https://posthoghelp.zendesk.com/agent/tickets/22132 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/24523)
https://posthoghelp.zendesk.com/agent/tickets/22652 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/25118)
