### ISSUE TITLE
Q1 2025: Joe's Goals

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/meta#261]
You'd think Q5 comes after [Q4](https://github.com/PostHog/meta/issues/243), but actually it's this. And 'this' is a plan that, as usual, I will continue to update throughout the quarter as I tick things off, plan things, and so on. 

So, what am I planning to do in Q1 2025? Well...

### Better beta programs 
- [x] [Document a waitlist process](https://github.com/PostHog/posthog.com/pull/10867) - Now doing via WIP page exports
- [x] Can we do waitlists in-app? (Prob not but [I'll try to code it](https://github.com/PostHog/posthog/pull/28935)) ([and again](https://github.com/PostHog/posthog/pull/29602)) (omg, [i actually did it](https://github.com/PostHog/posthog/pull/29602))
- [x] [Figure out, and start using, a method for beta activation](https://github.com/PostHog/posthog-js/pull/1624)
- [x] [Create an email flow to support users on beta programs](https://github.com/PostHog/meta/issues/262)
- [x] [Use all of the above to support the launch of error tracking](https://posthog.slack.com/archives/C0351B1DMUY/p1736256159084039)
- [ ] Make the beta onboarding flow collect feedback properly, betterly
- [x] [Get Zendesk feedback into BuildBettter too](https://posthog.slack.com/archives/C0351B1DMUY/p1741353412742179)
- [x] Roll beta promotion into [weekly digest](https://github.com/PostHog/meta/issues/259) (below)
- [x] [Improved beta guidelines](https://github.com/PostHog/posthog.com/pull/10712) 
- [x] Use all of the above to support the launch of [error tracking](https://github.com/PostHog/meta/issues/297) and LLM observability
- [x] Discuss with Brian the idea of advertising betas as early product previews, hand over to him to do this

### Optimize email marketing for cross-sell 
- [x] [New designs, plz](https://github.com/PostHog/meta/issues/263)
- [x] New designs in the billing flow too
- [x] Completely rebuild all email flows to better focus on cross-sell
- [x] In particular focus on pushing replay adoption by D5
- [x] [Launch the weekly digest to promote cross-product activation](https://github.com/PostHog/meta/issues/259)
- [x] Create an email onboarding branch to unblock users with ingestion issues by D28
- [x] Strongly focus the startup programs on encouraging warehouse adoption
- [x] Re-jig how case studies are used to bring out the cross-sell angle 
- [x] [Launch the hackathon weekly digest project as an A/B test](https://github.com/PostHog/meta/issues/259)

### Sidequest: Stay on top of paid ads
- [x] Continue managing our digital agency and just generally plug the gap here
- [x] Make sure we have a tie-in campaign to support the billboard ads
- [x] [Hire an Ads Person With Good Taste](https://posthog.com/careers/ads-person-with-good-taste)

### Sidequest: Plan out future hiring for the Words & Pictures team 
- [x] [Onboard Kevan](https://github.com/PostHog/company-internal/issues/1638#event-15625436858)
- [x] And [Brian](https://posthog.com/careers/ads-person-with-good-taste)
- [x] [Plan the next hires](https://github.com/PostHog/company-internal/issues/1696)
- [x] Team restructure and marketing org bits 

### Sidequest: Don't get distracted by boring partnerships
- [x] Do the AWS partnership and basically nothing else unless it's obviously amazing
- [x] Good lord, partnerships are so boring

### Sidequest: Reduce churn in group analytics ([Context](https://posthog.slack.com/archives/C083V7C6GKE/p1734063055828149), starts at 5.8%)
- [ ] [Pursue a Groups case study (with emphasis on cross-sell)](https://github.com/PostHog/posthog.com/issues/10341)
- [x] Create a post-subscription email flow to encourage usage

## Personal goals and Q4 Feedback
I collected some great 360 feedback in Q4 which [I detailed here](https://github.com/PostHog/meta/issues/243#issuecomment-2489817450). As a personal goal I want to continue focusing on some of this stuff in order to improve. Quick summary below to avoid repeating the previous issue, while still keeping it visible and current. 

#### Things to keep doing
Things that people liked and which they encouraged me on were...
- _Breadth_. There was feedback that people appreciate the breadth and volume of my work, so that's nice.
- _Organization_. It's scary, but apparently I'm one of the more organized people at the company? Crikey.
- _Leadership_. There was feedback that people like my management style and hiring choices, which is cool.
- _Writing_. It gets better the braver and weirder I make it, apparently.  

#### Things to stop doing
Things that people gave constructive feedback on were...
- _Noisiness_. I had feedback that I don't give enough space for others in conversation, which I really want to solve for. 
- _Anxiety_. 'Don't worry' is easier said than done, but I can at least not let my anxieties be infectious, right?

**Comment by charlescook-ph** [comment]
Looks good!

- Missed opportunity to call these Joals?
- Better beta programs -> Betah programs?

**Comment by joethreepwood** [comment]
Added some more ideas for the better betas goal...
