### ISSUE TITLE
Data Exploration next steps

### ISSUE THREAD

**Issue by mariusandra** [PostHog/meta#81]
# Data Exploration RFC v2

Listing the current status and (some of) the next steps. Some of these could get their own issues.

## Frontend

Goal: any uniquely separate part of any page is representable with a `json` query, which is passed to a <Query query={} /> component

- Insights and most tables in the app are already rendered via queries.
- Most queries are built from as an interface node that nests a data node
- Most components reuse `dataNodeLogic` to fetch the data from the backend
- Each interface node is in its folder under `frontend/src/queries/nodes/`
- Some scenes (that are not implemented!) could be made up of multiple queries (dashboards), or multiple inlined queries (trends chart is a combination of event list queries)

### TODO
- [ ] Port over insights and their filters to use data exploration natively
- [ ] Port over dashboards to store data exploration queries (not blocked by insights - there are already new insight nodes we can use)
- [ ] Get rid of antd
- [ ] Make `<Query query={} />` something any other React app can import and use
- [ ] Make the Query tab work with sidebar apps.
- [ ] Add throttling, caching and timeouts to `dataNodeLogic`, especially for dashboards.
- [ ] [Fix data table regressions](https://github.com/PostHog/posthog/issues/13223)

## Backend

Goal: all API endpoints should be made to `/api/projects/1/query`, and routed to a parser that converts them to ClickHouse SQL and returns the response.

- All API endpoints and their responses will be typed
- We will deprecate current endpoints like /events, /persons, etc when this goes live
- Currently all API endpoints are routed on the frontend to the old endpoints via `query.ts`

### TODO
- [ ] Create the endpoint and a router on the backend. This can be a REST router, or we could refactor all relevant API endpoints into service objects, and call those directly
- [ ] Remove routing from the frontend

## Query builder

- Our query builder is essentially sequential. Statement after statement, it checks `request.GET.get("bla")` for guidance, updates magic "arguments_list" style arrays, and pipes it all to a SQL f-string in the end. 
- Could we "compute" some of our queries in a more functional way? Think of rendering a ClickHouse query from a HogQL query in the same way React renders an interface from nested JSX nodes. Think `ast.visit` and map reduce, not `if params[:orderBy] query += "order by bla"`
- We also have "HogQL expressions", which let us safely convery any python-compatible SQL-like stirng into safe ClickHouse. These are currently only used when selecting columns from the events list.

### TODO
- [ ] Investigate and spec out ways we could make our query builder lean in to the AST-like nature of its input.
- [ ] Create an interface to enter a HogQL expression in the app's UI
- [ ] Investigate if we should use HogQL expressions in property filters
- [ ] Breakdowns by any HogQL expression in insights

## Event table breakdowns

- [ ] Rework the Column Configurator to support formulas and aggregations
- [ ] Make all aggregated columns clickable -> expands and shows the list behind the numbres
- [ ] Get "load next" working
- [ ] Do a lot of performance work
- [ ] Add support for pivot tables

## Pivot tables
- [ ] Map out the problem space on the query level
- [ ] Add the relevant parameters to the data node queries
- [ ] Add the right elements to the interface

## Query schema

- [ ] Go over all node kinds, make sure the naming is right
- [ ] Go over all nodes, look for inconsistencies
- [ ] Rename all files as needed
- [ ] Create a HogQL language design document
- [ ] Investigate using a better AST engine. Ideally cross platform.
- [ ] Look that exports contain correct columns

**Comment by danielthedifficult** [comment]
Just came here to say I love this feature, it's solving a problem I was trying to figure out myself just now, and that you're a beast for working on this.
