### ISSUE TITLE
Product for Engineers launch to do list 

### ISSUE THREAD

**Issue by andyvan-ph** [PostHog/meta#94]
### On Substack
- [x] [Plan for 1st issue](https://github.com/PostHog/posthog.com/issues/5309)
- [ ] Plan for 2nd issue
- [x] Write draft first issue for feedback
- [x] Write newsletter About page
- [x] Write newsletter Welcome email
- [x] Import existing mailing list
- [x] [1100 x 220 email banner image](https://github.com/PostHog/meta/issues/95)
- [x] [600 x 600 cover photo](https://github.com/PostHog/meta/issues/95)
- [x] [300 x 300 square logo image](https://github.com/PostHog/meta/issues/95)
- [x] Decide on newsletter URL

### On PostHog website

- [x] Update newsletter signup box
- [ ] Update newsletter signup page (posthog.com/newsletter)

**Comment by andyvan-ph** [comment]
## Newsletter Issue Theme Ideas

### Talking To Users

- **Original Blog Post:** How we do user interviews at PostHog
  - Should include acquisition, interview process, and how information is shared with teams.
  - How have user interviews influenced our product / strategy

**PostHog Tutorials:**
- (New) Introduction to the User Interview app / How to organise user interviews using PostHog

**Curated Articles:**
- TBC

**Book Recommends:** 
- The Mom Test by Rob Fitzpatrick
- Continuous Discovery Habits by Teresa Torres
- Nonviolent Communication by Marshall Rosenberg

### Other theme ideas
- New User Onboarding (how to improve it / understand it / how other companies do it)
- Pricing (might need to break this down into a few separate issues)
- Running experiments (best practices with practical examples)
- Measuring feature success / adoption 
- Power users (how to find them, what to learn about them, why they matter)
- Running hackathons (how we do them + benefits for your product)
- User Psychology / How Users Think (how users think, see: https://growth.design/psychology)

**Comment by andyvan-ph** [comment]
Outline for first issue: https://github.com/PostHog/posthog.com/issues/5309

**Comment by andyvan-ph** [comment]
FAO @corywatilo / @smallbrownbike

Substack supports custom domains with a trivial one-off $50. Documentation here: https://support.substack.com/hc/en-us/articles/360051222571-How-do-I-set-up-my-custom-domain-

My feeling is it would be best to setup our Substack on a sub-domain like `newsletter.posthog.com`. Any objections?

**Comment by corywatilo** [comment]
@smallbrownbike @pjhul Would we technically be able to do a proxy for this? (posthog.com/newsletter vs a subdomain)

**Comment by smallbrownbike** [comment]
@smallbrownbike P sure we can reverse proxy with Vercel. I'll find out.
